name: Build Dawn (Windows static x86)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dockcross/windows-static-x64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            mingw-w64 \
            mingw-w64-x86-64-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            mesa-common-dev \
            libx11-xcb-dev \
            pkg-config \
            nodejs \
            npm \
            python3 \
            python3-pip \
            git

      - name: Clone Dawn
        run: | 
          python3 tools/fetch_dawn_dependencies.py

      - name: Configure with CMake
        run: |
          mkdir -p out/Debug
          cd out/Debug
          cmake ../..

      - name: Build Dawn
        run: |
          cd out/Debug
          make VERBOSE=1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dawn-windows-static-x86
          path: dawn/out/Debug
