name: Build Dawn (Windows static x86)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up dockcross
        run: |
          docker pull dockcross/windows-static-x86
          docker run --rm dockcross/windows-static-x86 > ./dockcross
          chmod +x ./dockcross

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            mesa-common-dev \
            libx11-xcb-dev \
            pkg-config \
            nodejs \
            npm \
            python3 \
            python3-pip

      - name: Clone Dawn
        run: |
          git clone https://dawn.googlesource.com/dawn dawn
          cd dawn
          python3 tools/fetch_dawn_dependencies.py

      - name: Configure with CMake
        run: |
          cd dawn
          mkdir -p out/Debug
          cd out/Debug
          ../../dockcross cmake ../..

      - name: Build Dawn
        run: |
          cd dawn/out/Debug
          ../../dockcross make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dawn-windows-static-x86
          path: dawn/out/Debug
